### ISSUE TITLE
Method to load in repository configuration

### ISSUE THREAD

**Issue by daurnimator** [mgoltzsche/helm-kustomize-plugin#2]
I saw a TODO to allow loading in repository config at https://github.com/mgoltzsche/helm-kustomize-plugin/blob/b891cf188f8b1c74acf68aa6aa4141811ccde5e4/pkg/helm/helm.go#L72

For my particular case, I'd like to run from ArgoCD, which has repositories configured in it: I should be able to point helm-kustomize-plugin at them somehow.

**Comment by mgoltzsche** [comment]
@daurnimator thanks for reporting that issue! I totally agree that this todo there should be resolved.
Some time ago I already wondered if I shouldn't have used the helm binary instead of compiling it into the plugin binary. That could have solved this issue as well.

However currently I don't have time to look into this unfortunately.
Though would you like to create PR?

**Comment by mgoltzsche** [comment]
@daurnimator now the repository credentials are picked up from the configuration in helm home (if helm's `repositories.yaml` has an entry with an URL that matches the chart's repository URL its auth configuration is used to load the chart).
Therefore helm repository credentials can be managed as usual using `helm repo add`.
