### ISSUE TITLE
How to handle `.Capabilities.APIVersions.Has`

### ISSUE THREAD

**Issue by daurnimator** [mgoltzsche/helm-kustomize-plugin#7]
Various helm charts use `.Capabilities.APIVersions.Has` to change their behaviour based on resource types available in the destination cluster.
https://helm.sh/docs/chart_template_guide/function_list/#capabilitiesapiversionshas

How can I tell the chart inflator that different capabilities are available?

**Comment by mgoltzsche** [comment]
kustomize is actually just a renderer and has no idea about the k8s cluster the rendered resources are deployed in. Correspondingly this helm plugin has no idea about the target k8s cluster either currently.
How is this solved in `helm template`? Is it querying the k8s API based on some option or config file?
Ideally that information should be statically configurable since, in many workflows, the rendered manifest will be rendered into a git repo by a CI pipeline before a CD pipeline with access to a concrete k8s cluster applies it.

**Comment by daurnimator** [comment]
>  How is this solved in `helm template`? Is it querying the k8s API based on some option or config file?

Found https://github.com/helm/helm/pull/5392

Looks like you pass a series of `--api-version` arguments to helm when invoking it.
I guess we should have a field in the renderer config that contains an array of api versions to pass along to helm?

**Comment by mgoltzsche** [comment]
Sounds good! We could indeed add such a field to the generator resource.
A PR would be welcome.

**Comment by mgoltzsche** [comment]
@daurnimator there's now a `apiVersions` field supported within the generator resource (see `conditionalcr` example).
